project:
  type: book
  output-dir: docs

book:
  title: "Statistics and Machine Learning"
  author: "Yair Mau"
  repo-url: https://github.com/yairmau/statistics/
  favicon: archive/logo.png

  # date: "29.3.2025"
  chapters:
    - index.qmd
    - part: "data"
      chapters:
        - data/height.ipynb
        # - data/weight.ipynb
    - part: "hypothesis testing"
      chapters:
        - t_test/t_test_one_sample.ipynb
        - t_test/t_test_independent_samples.ipynb
    - part: "confidence interval"
      chapters:
        - confidence_interval/basic_concepts.ipynb
        - confidence_interval/analytical_confidence_interval.ipynb
        - confidence_interval/empirical_confidence_interval.ipynb
    - part: "permutation"
      chapters:
        - permutation/problem-with-t-test.ipynb
        - permutation/permutation.ipynb
        - permutation/numpy-vs-pandas.ipynb
        - permutation/exact-vs-montecarlo.ipynb
    - part: "regression"
      chapters:
        - regression/geometry-of-regression.ipynb
        - regression/least-squares.ipynb
        - regression/equivalence.ipynb
        - regression/mixed-model.ipynb
    - part: "miscellaneous"
      chapters:
        - misc/trend_test.ipynb
    # - references.qmd
  sidebar:
    collapse-level: 2
    tools:
      - icon: house-fill
        href: https://yairmau.com/
    logo: archive/logo.png
  search: true

# bibliography: references.bib

format:
  html:
    theme:
    - flatly
    - custom.scss
    # - font_defs.css
    # css: styles.css
    fontsize: 1.2em
    highlight-style: kate-custom.theme #kate #solarized # kate # tango # breeze # ayu # monokai # breezedark # espresso
    include-in-header:
      - includes.html
    code-line-numbers: true
    code-tools:
      source: repo  # https://quarto.org/docs/output-formats/html-code.html#code-tools
    callout-icon: false
    fig-align: center
    # the default MathJax rendering option yields ugly results, use katex
    html-math-method: katex
  
  pdf:
    documentclass: scrreprt
    include-in-header:
      - latex_preamble.tex



